// <auto-generated />
namespace GTMP_Database_GameMode.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GarageEnableDisableFnc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GarageEnableDisableFnc));
        
        string IMigrationMetadata.Id
        {
            get { return "201805121050297_GarageEnableDisableFnc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
